Fail sensibly on unsupported systems.

diff --git a/startup.in b/startup.in
--- a/startup.in
+++ b/startup.in
@@ -35,6 +35,9 @@ then
         service iptables save
     fi
     adduser --password '*' --comment "$gecos" "$user"
+else
+    printf 'startup: error: this system is not supported\n' "$0"
+    exit 1
 fi
 su "$user" -c 'mkdir -m 700 ~/.ssh'
 su "$user" -c 'cat > ~/.ssh/authorized_keys' < .ssh/authorized_keys
